version: "3.3"
services:
  counter-app:
    build:
      context: .
      dockerfile: views-counter-app/Dockerfile
    container_name: 'counter-app'
    ports:
      - 4000:4000
    environment:
      PORT: 4000
  library-app:
    build:
      context: .
      dockerfile: library-app/Dockerfile
    container_name: 'library-app'
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      COUNTER_URL: counter-app://counter-app:4000